apiVersion: v1
kind: Pod
metadata:
  name: croc-hunter
  labels:
    app: croc-hunter
spec:
  containers:
    - name: croc-hunter
      image: quay.io/lachie83/croc-hunter:v1
      ports:
        - containerPort: 8080
      volumeMounts:
      - mountPath: /test-pd
        name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /data