apiVersion: v1
kind: ReplicationController
metadata:
  name: croc-hunter
spec:
  replicas: 3
  selector:
    app: croc-hunter
  template:
    metadata:
      name: croc-hunter
      labels:
        app: croc-hunter
    spec:
      containers:
      - name: croc-hunter
        image: quay.io/lachie83/croc-hunter:v1
        ports:
        - containerPort: 8080